app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::when('admin*', 'sentry');
Route::when('api*', 'sentry');

Route::get('/login', function () {
    return View::make('users.login');
});

Route::group(array(
//    'prefix' => LaravelLocalization::setLocale(),
    'prefix' => 'old',
//    'before' => 'LaravelLocalizationRedirectFilter'
    ), function () {
    
    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Route::get('/', function () {
        return View::make('inicio')
                ->with('proyectos', Proyecto::where('visible', 1)->orderBy('fecha_fin', 'desc')->take(8)->get())
                ->with('areas', Area::all());
    });
    Route::get('/nosotros', function () {
        return View::make('quienes-somos');
    });
    Route::get('/servicios', function () {
        return View::make('servicios')
                ->with('areas', Area::all())
                ->with('tipos', Tipo::all())
                ->with('proyectos', Proyecto::all());
    });
    Route::get('servicios/proyecto/{id}', function ($id) {
        $proyecto = Proyecto::find($id);
        $anterior = Proyecto::where('visible', 1)->where('id', '<', $proyecto->id)->max('id');
        $siguiente = Proyecto::where('visible', '==', true)->where('id', '>', $proyecto->id)->min('id');
        return View::make('proyecto')
                ->with('proyecto', $proyecto)
                ->with('idSiguiente', $siguiente)
                ->with('idAnterior', $anterior);
    });
    Route::get('/internacionalizacion', function () {
        return View::make('internacionalizacion');
    });
    Route::get('/calidad', function () {
        return View::make('calidad');
    });
    Route::get('/idi', function () {
        return View::make('idi')
                ->with('articulos', Articulo::with('adjunto')->get())
                ->with('proyectosIdi', ProyectoIdi::all());
    });
    // Route::get('/contacto', function () {
    //     return View::make('contacto');
    // });
    Route::controller('contacto', 'ContactoController');
});

/** OTHER PAGES THAT SHOULD NOT BE LOCALIZED **/

Route::get('admin/', function () {
    return View::make('admin.admin')
            ->with('userEmail', Sentry::getUser()->email);
});

Route::group(array(
//    'prefix' => 'web',
), function () {

    Route::get('/', function () {
        return View::make('frontend.home')
            ->with('proyectos', Proyecto::where('visible', 1)->orderBy('fecha_fin', 'desc')->take(8)->get())
            ->with('areas', Area::all());
    });


     Route::get('comunicacion', function () {
        return View::make('frontend.comunicacion')
            ->with('articulos', Articulo::with('adjunto')->get())
            ->with('proyectosIdi', ProyectoIdi::all())
            ->with('noticias', Noticia::orderBy('fecha', 'desc')->get());
            
    }); 

     Route::get('documentacion', function () {
        return View::make('frontend.documentacion')
            ->with('articulos', Articulo::with('adjunto')->get())
            ->with('proyectosIdi', ProyectoIdi::all())
            ->with('pgou_docs', PgouDoc::orderBy('fecha', 'asc')->get())
            ->with('participacion_docs', ParticipacionDoc::orderBy('fecha', 'asc')->get())
            ->with('regeneracion_docs', RegeneracionDoc::orderBy('fecha', 'asc')->get());
            
    }); 

    Route::get('preliminar', function () {
        return View::make('frontend.preliminar');
    });

    Route::get('cofinanciacion', function () {
        return View::make('frontend.cofinanciacion');
    });    

    Route::get('contacto', function () {
        return View::make('frontend.contacto');
    });


    Route::post('contacto', function () {
        try {
            $datos = Input::all();
            Mail::send('contacto.email', $datos, function ($m) use ($datos) {
                $m->from('alcaladexivert@planifica.org', 'Web de planifica');
                $m->to('alcaladexivert@planifica.org')->subject('Web de planifica');
            });
            return Response::json(['success' => true]);
        } catch (Exception $e) {
            return $e;
            return Response::json(['success' => false]);
        }
    });

    Route::get('politica-cookies', function () {
        return View::make('frontend.politica_cookies');
    });

    Route::get('politica-privacidad', function () {
        return View::make('frontend.politica_privacidad');
    });

    Route::get('aviso-legal', function () {
        return View::make('frontend.aviso_legal');
    });
});

Route::controller('user', 'UserController');

Route::resource('api/v1/areas', 'AreaController');
Route::resource('api/v1/tipos', 'TipoController');
Route::resource('api/v1/proyectos', 'ProyectoController');
Route::resource('api/v1/proyectos.areas', 'ProyectoAreasController');
Route::resource('api/v1/proyectos.tipos', 'ProyectoTiposController');
Route::resource('api/v1/articulos', 'ArticuloController');
Route::resource('api/v1/proyectos_idi', 'ProyectoIdiController');
Route::resource('api/v1/proyectos.imagenes', 'ImagenController');
Route::resource('api/v1/adjuntos', 'AdjuntoController');

app/models/Area.php
<?php
class Area extends Eloquent
{
    
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'pla_areas';

    protected $fillable = array('nombre_es', 'nombre_en', 'nombre_fr', 'descripcion_es', 'descripcion_en', 'descripcion_fr');
    
    public function tipos() {
        return $this->hasMany('Tipo', 'id_pla_areas');
    }

    public function proyectos() {
        return $this->hasManyThrough('Proyecto', 'ProyectoArea', 'id_pla_areas', 'id');
    }
    
    public function getNombre() {
        if (App::getLocale() == 'es') {
            return $this->nombre_es;
        } elseif (App::getLocale() == 'en') {
            return $this->nombre_en;
        } elseif (App::getLocale() == 'fr') {
            return $this->nombre_fr;
        }
    }
    
    public function getDescripcion() {
        if (App::getLocale() == 'es') {
            return $this->descripcion_es;
        } elseif (App::getLocale() == 'en') {
            return $this->descripcion_en;
        } elseif (App::getLocale() == 'fr') {
            return $this->descripcion_fr;
        }
    }
}

app/models/Articulo.php
<?php
class Articulo extends Eloquent
{
    
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'pla_articulos';

    protected $fillable = array('nombre_es', 'nombre_en', 'nombre_fr', 'titulo_es', 'titulo_en', 'titulo_fr', 'autores', 'fecha', 'id_pla_adjuntos');
    
    public function adjunto() {
        return $this->belongsTo('Adjunto', 'id_pla_adjuntos');
    }
    
    public function getNombre() {
        if (App::getLocale() == 'es') {
            return $this->nombre_es;
        } elseif (App::getLocale() == 'en') {
            return $this->nombre_en;
        } elseif (App::getLocale() == 'fr') {
            return $this->nombre_fr;
        }
    }
    
    public function getTitulo() {
        if (App::getLocale() == 'es') {
            return $this->titulo_es;
        } elseif (App::getLocale() == 'en') {
            return $this->titulo_en;
        } elseif (App::getLocale() == 'fr') {
            return $this->titulo_fr;
        }
    }
}

app/views/frontend/cofinanciacion.blade.php
@extends('frontend.layout.base')

@section('contenido')

  <section id="page-title" class="page-title-video text-light"
           data-vide-bg="mp4:{{ url('frontend/video/encuesta') }}, poster:{{ url('frontend/video/encuesta_poster') }}"
           data-vide-options="position: 0% 70%"
           style="background: rgba(80,99,128,0.60);">
    <div class="container">
      <div class="page-title col-md-8">
        <h1>{{ trans('general.cofinanciacion_seccion.titulo') }}</h1>
      </div>
      <div class="col-md-12">
        <h4 class="text-center" style="font-size: 2.5rem;font-weight: 100;">{{ trans('general.documentacion_seccion.subtitulo') }}</h4>
      </div>
    </div>
  </section>

  <section class="container p-t-40 p-b-40">
    <div class="row">
      <img class="img-responsive col-md-8 col-md-offset-2" style="margin-top: 70px" src="{{ asset('frontend/img/logo/edusi_lliria.png') }}" alt="edusi_vinaros"><br>
    </div>
    <div class="row">
      <p class="text-justify lead">
        Los Fondos Estructurales y de Inversión Europeos son unos fondos que funcionan de modo conjunto a fin de apoyar la cohesión económica, social y territorial y alcanzar los objetivos de la Estrategia Europa 2020 de la Unión Europea (UE) para un crecimiento inteligente, sostenible e integrador. El Fondo Europeo de Desarrollo Regional (FEDER) es uno de ellos. 
      </p>
      <p class="text-justify lead">
        Por resolución de 18 de mayo de 2018, de la Presidencia de la Generalitat (DOGV 8301 de 23 de mayo de 2018) se resolvió la concesión de las ayudas convocadas por la citada resolución de 20 de noviembre de 2017, de la Presidencia de la Generalitat destinadas a subvencionar proyectos locales de actuación de los municipios de la Comunitat Valenciana de fomento de la movilidad urbana sostenible susceptibles de cofinanciación por los Programas Operativos FEDER de la Comunitat Valenciana 2014-2020.
      </p>
      <!-- <p class="text-justify lead">
        El Ayuntamiento de Vinaròs fue una de las entidades locales beneficiarias para la redacción del Plan de Movilidad Urbana Sostenible (PMUS) del municipio. 
      </p> -->
    </div>
  </section>

  <!-- <section class="container">
    <iframe src="http://mapifica.org/pmu_vinaros/index.html" style="border:none;height: 800px;width:100%;"></iframe>
  </section>
 -->

@endsection

app/views/frontend/comunicacion.blade.php
@extends('frontend.layout.base')

@section('contenido')

  <section id="page-title" class="page-title-video text-light"
           data-vide-bg="mp4:{{ url('frontend/video/encuesta') }}, poster:{{ url('frontend/video/encuesta_poster') }}"
           data-vide-options="position: 0% 70%"
           style="background: rgba(80,99,128,0.60);">
    <div class="container">
      <div class="page-title col-md-8">
        <h1>{{ trans('general.comunicacion_seccion.titulo') }}</h1>
      </div>
      <div class="col-md-12">
        <h4 class="text-center" style="font-size: 2.5rem;font-weight: 100;">{{ trans('general.comunicacion_seccion.subtitulo') }}</h4>
      </div>
    </div>
  </section>

  <section class="container">
   @foreach ($noticias as $noticia)
      <div class="row justify-content-start">

             <!--Featured image-->
        
                  <div class="col-sm-6">
                      <div class="view overlay hm-white-light z-depth-1-half">
                          <img src="{{ $noticia->getImagen() }}" class="img-fluid" alt="" style="width:100%">
                          <div class="mask"></div>
                      </div>
                  </div>
      <!--/.Featured image-->
       
       <!--Second column-->
          <div class="col-sm-6">
              <!--Excerpt-->

            <h4>{{ $noticia->getTitulo() }}</h4>
             <p>{{ $noticia->getTexto() }}</p>
             <p><em>{{ $noticia->getFecha() }}</em></p>
             @if ($noticia->getLink() != null)
              <a href="{{ $noticia->getLink() }}" target="_blank" class="button color" role="button">{{ $noticia->getTexto_boton() }}</a>
             @endif
              
      </div>
          <!--/Second column-->
         
      </div>
      <br><br>
      <hr>
   @endforeach
  </section>

@endsection

app/views/frontend/contacto.blade.php
@extends('frontend.layout.base')

@section('contenido')

<section id="page-title" class="page-title-video text-light p-t-100 p-b-40" data-vide-bg="mp4:{{ url('frontend/video/computer') }}, poster:{{ url('frontend/video/computer') }}" data-vide-options="position: 50% 50%"
         style="background: rgba(80,99,128,0.60);">
  <div class="container">
    <div class="page-title col-md-12 text-center">
      <h2 class="m-b-20">{{ trans('general.contacto_seccion.titulo') }}</h2>
    </div>
    <div class="col-md-12 text-center text-lg">
      <h1><a href="mailto:pmuslliria@planifica.org" class="button large transparent rounded contacto-mail text-lg"
             style="
                    /*font-size: 4vw;*/
                    text-transform: none;
                    line-height: 0rem;
                    padding: 3rem;text-transform: none;"
                >
          pmuslliria@planifica.org
        </a></h1>
    </div>
  </div>
</section>

<section class="p-t-40">

  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xs-12 contacto-direcciones">
        <h3>Dónde estamos</h3><br>
        <h4>Llíria (Valencia)</h4>
        <h5>Departamento de Urbanismo del Ayuntamiento de Llíria</h5>

        <p>Pl. Mayor, 1<br>
          46160, Llíria (Valencia)<br>
          <div>
          Web: lliria.es</p>
          </div><br>
        <h4></h4>
        <h5>PLANIFICA</h5>

        <p>Calle Poeta Guimerá, 7 - 5A<br>
          12001, Castellón<br>

        <div>
          Telf: (+34) 964 06 12 56<br>
          Email: pmuslliria@planifica.org<br>
          Web: planifica.org</p>
        </div>
      </div>

      <div class="col-md-8 col-xs-12">
        <form id="contacto" action="" class="form-gray-fields" role="form" method="post">
          <div class="row">
            <div class="col-md-5">
              <div class="form-group">
                <label class="upper" for="name">{{ ucfirst(trans('general.nombre')) }}</label>
                <input type="text" class="form-control" name="name" placeholder="{{ ucfirst(trans('general.nombre_placeholder')) }}" id="name"
                       minlength="2" required
                        >
              </div>
            </div>
            <div class="col-md-7">
              <div class="form-group">
                <label class="upper" for="email">{{ ucfirst(trans('general.email')) }}</label>
                <input type="email" class="form-control email" name="email" placeholder="{{ ucfirst(trans('general.email_placeholder')) }}"
                       id="email"
                       aria-required="true" required
                        >
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label class="upper" for="comment">{{ ucfirst(trans('general.comentario')) }}</label>
                <textarea class="form-control" name="comment" rows="9" placeholder="{{ ucfirst(trans('general.comentario_placeholder')) }}"
                          id="comment"
                          aria-required="true" required
                        ></textarea>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-left">
                <button class="button small icon-left color" type="submit"><i class="fa fa-paper-plane"></i>&nbsp;{{ ucfirst(trans('general.enviar')) }}
                </button>
                 <span id="span-terminos">
                   <input name="terminos" type="checkbox" value="1" id="terminos" class="required" style="margin-left: 10px;" required>
                  Acepto la <a target="_blank" href="{{ url('aviso-legal') }}"
                               style="">política de
                     protección de datos</a>
                   </span>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 p-b-20">
              <div id="contacto-loading" style="display: none">
                <div class="text-center" style="background: #DEDEDE;padding: 15px;">
                  <img width="50px" src="{{ url('frontend/img/svg-loaders/three-dots.svg') }}">&nbsp;&nbsp;Enviando mensaje...
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div id="contacto-success" class="contacto-mensajes">
                Tu mensaje se ha enviado con éxito. En breve nos pondremos en contacto contigo.
              </div>
              <div id="contacto-fail" class="contacto-mensajes">
                Hay un porblema al enviar el mensaje. Envianos un correo a <b>info@planifica.org</b>
              </div>

            </div>
          </div>
          <div class="clear"></div>
          <div class="row">
            <div class="col-md-12">
              <p class="textarea-block" style="font-size: 11px;line-height: 20px;">
                Protección de datos personales: <b>PLANIFICA</b> le informa de que la recogida de sus datos de carácter personal se produce con los
                siguientes
                fines: (i) gestionar y tramitar cada uno de los servicios solicitados por el Usuario (ii) comerciales y publicitario respecto de productos,
                servicios,
                ofertas, promociones, y cualesquiera otras actividades publicitarias, y, (iii) realizar encuestas, estadísticas y análisis de mercado. El
                Usuario
                podrá ejercer los derechos de acceso, rectificación, cancelación y oposición de sus datos de carácter personal, en los términos establecidos en
                la
                LOPD, dirigiéndose por escrito a la siguiente dirección: PLANIFICA, C/San Vicente, 4 3º 12002 - Castellón, o bien enviando un email a la
                dirección
                info@planifica.org.
              </p>
            </div>
          </div>
        </form>
        <script type="text/javascript">
          $(document).ready(function () {
            $("#contacto").validate({
              submitHandler: function (form) {
                $('#span-terminos').removeClass('error')
                sendmail();
              },
              invalidHandler: function (event, validator) {
                if ($(this).find('#terminos').is(':checked')) {
                  $('#span-terminos').removeClass('error')
                } else {
                  $('#span-terminos').addClass('error')
                }
              }
            });
          });

          function sendmail() {
            $('#contacto-loading').show();
            var data = $('#contacto').serializeArray();
            var url = "{{ url('contacto')}}";
            $.ajax({
              cache: false,
              url: url,
              data: data,
              type: 'POST',
              success: function (data) {
                if (data.success == true) {
                  $('#contacto-loading').hide();
                  $('#contacto-fail').hide();
                  $('#contacto-success').show();
                  $('form')[0].reset();
                } else {
                  $('#contacto-loading').hide();
                  $('#contacto-fail').show();
                }
              },
              error: function (ajaxContext) {
                console.log(ajaxContext);
                alert(ajaxContext.responseText)
              }
            });
          }
          $(function () {
            $('#contact').addClass('current');

            $('#reserva-success').hide();
            $('#reserva-loading').hide();
            $('#reserva-massages').hide();

          });
        </script>
      </div>

    </div>
    <!--END: Default Form-->
    <hr class="space">

  </div>

</section>

@endsection

app/views/frontend/documentacion.blade.php
@extends('frontend.layout.base')

@section('contenido')

  <section id="page-title" class="page-title-video text-light"
           data-vide-bg="mp4:{{ url('frontend/video/encuesta') }}, poster:{{ url('frontend/video/encuesta_poster') }}"
           data-vide-options="position: 0% 70%"
           style="background: rgba(80,99,128,0.60);">
    <div class="container">
      <div class="page-title col-md-8">
        <h1>{{ trans('general.documentacion_seccion.titulo') }}</h1>
      </div>
      <div class="col-md-12">
        <h4 class="text-center" style="font-size: 2.5rem;font-weight: 100;">{{ trans('general.documentacion_seccion.subtitulo') }}</h4>
      </div>
    </div>
  </section>

  <section class="p-t-40">
    <div class="container">
      <div id="tabs-05c" class="tabs color">
        <p class="lead">{{ trans('general.documentacion_seccion.texto') }}</p>
        <ul class="tabs-navigation">
          
          
          <li class="active"><a href="#doc_pgou">{{ trans('general.documentacion_seccion.doc_pgou') }}</a></li>
          <li><a href="#doc_regeneracion">{{ trans('general.documentacion_seccion.doc_regeneracion') }}</a></li>
          <li><a href="#doc_participacion">{{ trans('general.documentacion_seccion.doc_participacion') }}</a></li>
          
        </ul>
        <div class="tabs-content">
          
          <div class="tab-pane" id="doc_participacion">
            <ol class="ol-type1">
              @foreach ($participacion_docs as $participacion_doc)
                <li>
                  <strong>{{ $participacion_doc->getTitulo() }}</strong><br>
                  <span>{{ $participacion_doc->getDescripcion() }}</span>
                  
                  @if ($participacion_doc->getLink_1() != null)
                  <ul>
                    <li>    
                      <a href="{{ $participacion_doc->getLink_1() }}" target="_blank">
                        {{ $participacion_doc->getText_link_1() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($participacion_doc->getLink_2() != null)
                  <ul>
                    <li>    
                      <a href="{{ $participacion_doc->getLink_2() }}" target="_blank">
                        {{ $participacion_doc->getText_link_2() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($participacion_doc->getLink_3() != null)
                  <ul>
                    <li>    
                      <a href="{{ $participacion_doc->getLink_3() }}" target="_blank">
                        {{ $participacion_doc->getText_link_3() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($participacion_doc->getLink_4() != null)
                  <ul>
                    <li>    
                      <a href="{{ $participacion_doc->getLink_4() }}" target="_blank">
                        {{ $participacion_doc->getText_link_4() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($participacion_doc->getLink_5() != null)
                  <ul>
                    <li>    
                      <a href="{{ $participacion_doc->getLink_5() }}" target="_blank">
                        {{ $participacion_doc->getText_link_5() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                </li>
                <hr>
              @endforeach
            <ol>
          </div>


          <div class="tab-pane active" id="doc_pgou">
            <ol class="ol-type1">
              @foreach ($pgou_docs as $pgou_doc)
                <li>
                  <strong>{{ $pgou_doc->getTitulo() }}</strong><br>
                  <span>{{ $pgou_doc->getDescripcion() }}</span>
      
                  @if ($pgou_doc->getLink_1() != null)
                  <ul>
                    <li>    
                      <a href="{{ $pgou_doc->getLink_1() }}" target="_blank">
                        {{ $pgou_doc->getText_link_1() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($pgou_doc->getLink_2() != null)
                  <ul>
                    <li>    
                      <a href="{{ $pgou_doc->getLink_2() }}" target="_blank">
                        {{ $pgou_doc->getText_link_2() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($pgou_doc->getLink_3() != null)
                  <ul>
                    <li>    
                      <a href="{{ $pgou_doc->getLink_3() }}" target="_blank">
                        {{ $pgou_doc->getText_link_3() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($pgou_doc->getLink_4() != null)
                  <ul>
                    <li>    
                      <a href="{{ $pgou_doc->getLink_4() }}" target="_blank">
                        {{ $pgou_doc->getText_link_4() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($pgou_doc->getLink_5() != null)
                  <ul>
                    <li>    
                      <a href="{{ $pgou_doc->getLink_5() }}" target="_blank">
                        {{ $pgou_doc->getText_link_5() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($pgou_doc->getLink_6() != null)
                  <ul>
                    <li>    
                      <a href="{{ $pgou_doc->getLink_6() }}" target="_blank">
                        {{ $pgou_doc->getText_link_6() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                </li>
                <hr>
              @endforeach
            </ol>
          </div>


          <div class="tab-pane" id="doc_regeneracion">
            <ol class="ol-type1">
              @foreach ($regeneracion_docs as $regeneracion_doc)
                <li>
                  <strong>{{ $regeneracion_doc->getTitulo() }}</strong><br>
                  <span>{{ $regeneracion_doc->getDescripcion() }}</span>
                  
                  @if ($regeneracion_doc->getLink_1() != null)
                  <ul>
                    <li>    
                      <a href="{{ $regeneracion_doc->getLink_1() }}" target="_blank">
                        {{ $regeneracion_doc->getText_link_1() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($regeneracion_doc->getLink_2() != null)
                  <ul>
                    <li>    
                      <a href="{{ $regeneracion_doc->getLink_2() }}" target="_blank">
                        {{ $regeneracion_doc->getText_link_2() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($regeneracion_doc->getLink_3() != null)
                  <ul>
                    <li>    
                      <a href="{{ $regeneracion_doc->getLink_3() }}" target="_blank">
                        {{ $regeneracion_doc->getText_link_3() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($regeneracion_doc->getLink_4() != null)
                  <ul>
                    <li>    
                      <a href="{{ $regeneracion_doc->getLink_4() }}" target="_blank">
                        {{ $regeneracion_doc->getText_link_4() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                  @if ($regeneracion_doc->getLink_5() != null)
                  <ul>
                    <li>    
                      <a href="{{ $regeneracion_doc->getLink_5() }}" target="_blank">
                        {{ $regeneracion_doc->getText_link_5() }}
                      </a><br>
                    </li>
                  </ul>
                  @endif
                </li>
                <hr>
              @endforeach
            <ol>
          </div>
          
        </div>
      </div>
    </div>
  </section>

@endsection

app/views/frontend/documentacion_provi.blade.php
@extends('frontend.layout.base')

@section('contenido')

  <section id="page-title" class="page-title-video text-light"
           data-vide-bg="mp4:{{ url('frontend/video/encuesta') }}, poster:{{ url('frontend/video/encuesta_poster') }}"
           data-vide-options="position: 0% 70%"
           style="background: rgba(90,182,178,0.60);">
    <div class="container">
      <div class="page-title col-md-8">
        <h1>{{ trans('general.documentacion_seccion.titulo') }}</h1>
      </div>
      <div class="col-md-12">
        <h4 class="text-center" style="font-size: 2.5rem;font-weight: 100;">{{ trans('general.documentacion_seccion.subtitulo') }}</h4>
      </div>
    </div>
  </section>

  <section class="p-t-40">
    <div class="container">
      <div id="tabs-05c" class="tabs color">
        <p class="lead">{{ trans('general.documentacion_seccion.texto') }}</p>
        <ul class="tabs-navigation">
          <li class="active"><a href="#doc_pgou">{{ trans('general.documentacion_seccion.doc_pgou') }}</a></li>
          <li><a href="#doc_participacion">{{ trans('general.documentacion_seccion.doc_participacion') }}</a></li>
          
        </ul>
        <div class="tabs-content">
          <div class="tab-pane active" id="doc_pgou">
            <ol class="ol-type1">
              @foreach ($articulos as $articulo)
                <li>
                  <strong>{{ $articulo->getNombre() }}</strong><br>
                  {{ $articulo->fecha }}<br>
                  Título del artículo: <a @if ($articulo->adjunto != null) href="{{ URL::to($articulo->adjunto->ruta) }}" @endif target="_blank">
                    {{ $articulo->getTitulo() }}
                  </a><br>
                  Autores: {{ $articulo->autores }}
                </li>
              @endforeach
            </ol>
          </div>
          <div class="tab-pane" id="doc_participacion">
            <h4>{{ trans('general.documentacion_seccion.doc_participacion') }}</h4>
            <ol class="ol-type1">
              <li>
                <strong>BLUECITY [INTERREG IVC].</strong><br>
                Sistema de indicadores para la evaluación de la gestión del ciclo integral del agua en entornos urbanos.
              </li>
              <li>
                <strong>AQUAVAL [Programa Life+].</strong><br>
                La gestión eficiente del agua de lluvia en entornos urbanos (<a target="_blank" href="http://www.aquavalproject.eu/">www.aquavalproject.eu/</a>).

              </li>
              <li>
                <strong>E2Stormed [Programa MED].</strong><br>
                Mejora de la eficiencia energética en el ciclo del agua en ciudades mediterráneas mediante el uso de tecnologías
                innovadoras para la gestión del agua de lluvia (<a target="_blank" href="http://www.e2stormed.eu/">www.e2stormed.eu</a>).
              </li>
            <ol>
          </div>
          
        </div>
      </div>
    </div>
  </section>

@endsection